apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: corner
data:
  username: <INSERT_MONGO_ROOT_USERNAME_HERE>
  password: <INSERT_MONGO_ROOT_PASSWORD_HERE>
---
apiVersion: v1
kind: Secret
metadata:
  name: corner-credentials
  namespace: corner
data:
  password: <INSERT_SITE_ADMIN_PASSWORD_HERE>
