name: Auto-Release
on:
  release:
    types: [published]
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sventi555/corner/corner
          tag_with_ref: true
  update_cluster:
    if: github.event_name == 'release'
    needs: [push_to_registry]
    name: Update k8s cluster to use release version
    runs-on: ubuntu-latest
    steps:
    - name: Save DigitalOcean Kubernetes Config
      uses: matootie/dokube@v1.3.1
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        clusterName: sventis-cluster
        namespace: corner
    - name: Update StatefulSet
      run: kubectl set image statefulset.apps/corner corner="docker.pkg.github.com/sventi555/corner/corner:${GITHUB_REF##*/}"
    - name: Wait for StatefulSet
      run: kubectl rollout status statefulset/corner -w

